[package]
name = "string_wrapped"
version = "0.1.0"
authors = ["Niclas Rosengren <niclas.rosengren@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.92"

[dev-dependencies]
serde_json = "1.0.39"
